import Link from 'next/link';
import ArticleCard from '../components/ArticleCard';
import { articles, topics } from '../lib/content';
export default function Home(){const lead=articles[0]; return <main>
<section className="hero"><div className="hero-copy"><div className="eyebrow">RETINAL SCIENCE · TECHNOLOGY · CARE</div><h1>See What’s <em>Next.</em></h1><p>The technologies, research and ideas shaping the future of retinal care.</p><div className="hero-actions"><Link className="primary" href={`/article/${lead.slug}`}>Explore the lead story →</Link><Link className="secondary" href="/#latest">Browse latest</Link></div></div><div className="hero-art"><div className="hero-retina"><div className="optic-disc"/><div className="vessel v1"/><div className="vessel v2"/><div className="vessel v3"/></div><div className="hero-caption"><span>VISUAL FIELD / 01</span><b>Retina as interface</b></div></div></section>
<section className="lead-section"><div className="section-kicker"><span>01</span> LEAD STORY</div><ArticleCard article={lead} large/></section>
<section className="frontier"><div className="section-heading"><div><div className="section-kicker"><span>02</span> THE FRONTIER</div><h2>What’s moving now.</h2></div><p>Signals worth following across AI, imaging and translational research.</p></div><div className="frontier-grid">{articles.slice(1,5).map((a,i)=><Link key={a.slug} href={`/article/${a.slug}`} className="frontier-item"><span>0{i+1}</span><div className="eyebrow">{a.category}</div><h3>{a.title}</h3><p>{a.dek}</p></Link>)}</div></section>
<section id="latest" className="latest"><div className="section-heading"><div><div className="section-kicker"><span>03</span> LATEST</div><h2>Research, decoded.</h2></div><p>Clear reporting built around evidence, limitations and what comes next.</p></div><div className="cards-grid">{articles.slice(4).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section>
<section className="topics"><div className="section-kicker"><span>04</span> EXPLORE</div><div className="topic-grid">{topics.map((t,i)=><Link key={t.slug} href={`/topic/${t.slug}`}><span>0{i+1}</span><h3>{t.name}</h3><p>{t.dek}</p><b>Explore {t.name} →</b></Link>)}</div></section>
<section className="window"><div><div className="eyebrow">EMERGING FIELD</div><h2>The retina as a window.</h2><p>What can the eye reveal about the rest of the body? Follow the evidence around oculomics, retinal biomarkers and systemic health.</p><Link className="primary light" href="/article/retina-window-health">Explore the evidence →</Link></div><div className="window-art"><div className="rings"/><div className="axis x"/><div className="axis y"/></div></section>
<section id="brief" className="brief"><div className="eyebrow">THE RETINA BRIEF</div><h2>Five developments.<br/>Five minutes. Once a week.</h2><p>A concise evidence-conscious briefing on what changed in retinal science and why it matters.</p><form><input aria-label="Email address" type="email" placeholder="you@example.com"/><button type="button">Join the Brief →</button></form><small>V1 demo: connect this form to your email provider before launch.</small></section>
</main>}
